
import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "../components/Sidebar";
import SearchContainer from "../components/SearchContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {

    return (
        <html lang="en">
            <body className="flex bg-[#F7FBff] h-screen">
                <Sidebar/>
                <main className="p-10 max-w-7xl w-full mx-auto overflow-y-auto">
                    <SearchContainer/>
                    {children}
                </main>
            </body>
        </html>
    );
}
